# Generated by Django 5.0.4 on 2024-04-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Universo',
                'verbose_name_plural': 'Universos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('universe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_planets', to='planets.universe', verbose_name='Universo')),
            ],
            options={
                'verbose_name': 'Planeta',
                'verbose_name_plural': 'Planetas',
                'ordering': ['name'],
            },
        ),
    ]
